<style type="text/css"<?php echo $this->nonceAttr; ?>><?php
	include_once(__DIR__ . '/db.panel.css');
?></style>
<div class="tracy-panel-db">
	<h1>
		<span class="left">Database Panel</span>
		<span class="right">
			queires count: <?php echo $this->queriesCount; ?>,
			<span title="<?php echo number_format($this->queriesTime, 3, '.', ' '); ?>&nbsp;s">queires time: <?php echo number_format($this->queriesTime * 1000, 3, '.', ' '); ?>&nbsp;ms</span>
		</span>
	</h1>
	<div class="content" id="tracy-db-panel-content-<?php echo $this->panelId; ?>">
		<table>
			<thead>
				<tr>
					<th><a data-map="order" data-dir="1" class="asc" href="javascript:void(0);">Order</a></th>
					<th>Query</th>
					<th><a data-map="exec" data-dir="0" class="" href="javascript:void(0);">Execution&nbsp;time</a></th>
					<th>Stack</th>
					<th><a data-map="conn" data-dir="0" class="" href="javascript:void(0);">Connection</a></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->queries as $key => $item): ?>
					<tr 
						class="query-row<?php
							foreach (array_keys(static::$queryTypesColors) as $queryTypeFlag):
								if (($item->type & $queryTypeFlag) != 0):
									echo ' query-type-'.$queryTypeFlag;
								endif;
							endforeach;
						?>" 
						data-hash="<?php echo $item->hash; ?>" 
						data-row='{"exec":<?php echo $item->exec; ?>,"conn":<?php echo json_encode($item->connection); ?>}'>
						<td class="order"><?php echo number_format($key+1, 0, '', '&nbsp;'); ?></td>
						<td class="query"><div><?php
							echo '<code>', htmlspecialchars($item->query, ENT_QUOTES), '</code>';
							if ($item->params !== NULL)
								echo '<br /><br />' . \Tracy\Dumper::toHtml($item->params, [
									\Tracy\Dumper::COLLAPSE	=> FALSE,
									\Tracy\Dumper::LIVE		=> TRUE,
								])
						?></div></td>
						<td class="exec" title="<?php echo number_format($item->exec, 3, '.', '&nbsp;'); ?>&nbsp;s"><?php
							echo number_format($item->execMili, 3, '.', '&nbsp;');
						?>&nbsp;ms<div>
							Request:&nbsp;<?php echo $item->reqTime; ?><br />
							Response:&nbsp;<?php echo $item->resTime; ?>
						</div></td>
						<td class="stack"><div>
							<span class="info"><?php $stepsCount = count($item->stack); echo $stepsCount; ?>&nbsp;step<?php if ($stepsCount > 0) echo 's'; ?></span>
							<table class="steps"><tbody><?php
								foreach ($item->stack as $stackItem):
									list($fileLink, $phpCode) = $stackItem;
									?><tr><td class="link"><?php echo $fileLink; ?></td><td class="code"><?php echo $phpCode; ?></td></tr><?php
								endforeach;
							?></tbody></table>
						</div></td>
						<td class="conn"><?php echo $item->connection; ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<?php echo $this->debugCode; ?>
</div>
<script type="text/javascript"<?php echo $this->nonceAttr; ?>>
	<?php include_once(__DIR__ . '/db.panel.js'); ?>
	new Tracy.DebugDbPanel('tracy-db-panel-content-<?php echo $this->panelId; ?>');
</script>